UTIL_DS = '/'
ST_DEBUG = True 
SV_HOST = "127.0.0.1"
SV_PORT = 5000
SS_TKN_SIZE = 24
PW_MN_SIZE = 8
#SV_DIR_IMAGES ="images"
#TBL_TBUSERS ="prueba.tbusuarios"
#TBL_EVNT_USERS="prueba.evnt_usuarios"