#Errores controlados del sistema
ERR_NO_CMNQS_ADMNSTDR_STMA = "comuníquese con el administrador del sistema."
ERR_NO_USRO_CNTSN_INVLD = 'Usuario o Contraseña Invalida'
ERR_NO_INGSA_USRO = 'Debe ingresar su usuario'
ERR_NO_INGRSA_CNTRSNA = 'Debe ingresar su contraseña'
ERR_NO_DB_INGRSR_NVA_CNTRSNA = 'Debe ingresar su nueva contraseña'
ERR_NO_TKN_INVLDO = 'Token invalido'
ERR_NO_MNM_CRCTRS = 'El minimo de caracteres perminitidos es  6'
ERR_NO_MNMO_MYSCLA = 'Su contraseña de contener minimo una caracter en mayuscula'
ERR_NO_MNMO_NMRO = 'Su contraseña de contener minimo un número'
ERR_NO_TNE_PRMTDO_ACCDR = 'El usuario no tiene permitido acceder, '+ERR_NO_CMNQS_ADMNSTDR_STMA
ERR_NO_TNE_PRFL = 'El usuario no tiene un Perfil Asignado '+ERR_NO_CMNQS_ADMNSTDR_STMA
ERR_NO_USRO_INCTVO = 'Usuario Inactivo '+ERR_NO_CMNQS_ADMNSTDR_STMA
ERR_NO_SN_SSN = 'No se encuentra la sesión en el servidor'
ERR_NO_SN_PRMTRS = 'Sin Parametros'
ERR_NO_USRO_SN_MNU = 'Su Usuario No Cuenta con un Menu Asignado '+ERR_NO_CMNQS_ADMNSTDR_STMA
ERR_NO_SN_MNU_ASGNDO = 'Su Usuario No Cuenta con un Menu Asignado '+ERR_NO_CMNQS_ADMNSTDR_STMA
ERR_NO_Cdgo = 'Codigo Debe Contener Datos' 
ERR_NO_Dscrpcn = 'Descripcion Debe Contener Datos'
ERR_NO_NOBRE = 'Debe ingresar Ssu nombre'
ERR_NO_FTO = 'Debe ingresar una foto'
ERR_NO_ID  = 'ID Es Dato Obligatorio'