ERR_NO_00 = "comuníquese con el administrador del sistema."
ERR_NO_01 = 'Usuario o Contraseña Invalida'
ERR_NO_02 = 'Debe ingresar su usuario'
ERR_NO_03 = 'Debe ingresar su contraseña'
ERR_NO_04 = 'Debe ingresar su nueva contraseña'
ERR_NO_05 = 'Token invalido'
ERR_NO_06 = 'El minimo de caracteres perminitidos es  6'
ERR_NO_07 = 'Su contraseña de contener minimo una caracter en mayuscula'
ERR_NO_08 = 'Su contraseña de contener minimo un número'
ERR_NO_09 = 'El usuario no tiene permitido acceder, '+ERR_NO_00
ERR_NO_10 = 'El usuario no tiene un Perfil Asignado '+ERR_NO_00
ERR_NO_11 = 'Usuario Inactivo '+ERR_NO_00
ERR_NO_12 = 'No se encuentra la sesión en el servidor'
ERR_NO_13 = 'Sin Parametros'