#!/usr/bin/env python
# -*- coding: utf-8 -*-
lbl_nmbr_usrs = 'Nombre de usuario'
lbl_cntrsna_usrs = 'Contraseña de usuario'
lbl_nva_cntrsna = 'Nueva Contraseña'
lbl_cdgo_prfl = 'Codigo Perfil'
lbl_dscrpcn_prfl =  'Descripcion Perfil'
lbl_cdgo= 'Codigo'
lbl_prgnta= 'Descripcion Pregunta'
lbl_rspsta='Descripcion Respuesta'
lbl_lgn = 'Login' 
lbl_cntrsna =  'Contraseña'
lbl_id_prfl = 'id Perfil'
lbl_cntrsna = 'Login'
SCCSS_RGSTRO_EXTSO='El registro se inserto con Exito'
WRNNG_CDDO='¡Cuidado! Es muy importante que leas este mensaje de alerta.'
INFO_ATNCN='¡Atento! Este mensaje requiere de tu atención, aunque no es tan importante.'
SCCSS_ACTLZCN_EXTSA= 'Actualizacion exitosa'
INFO_NO_DTS ='¡Sin Datos En la Consulta!'